# Generated by Django 4.1.8 on 2023-05-30 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0005_alter_feedback_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='feedback',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='feedback.feedback'),
        ),
    ]
