# Generated by Django 4.1.8 on 2023-06-28 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0009_alter_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackimage',
            name='image',
            field=models.ImageField(upload_to='images/feedback'),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
