# Generated by Django 4.1.8 on 2023-06-28 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0010_alter_feedbackimage_image_delete_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackimage',
            name='caption',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
